### ISSUE TITLE
Ask for makefile & how to implement new device on verstatilepb

### ISSUE THREAD

**Issue by EvaChenn** [grandemk/qemu_devices#2]
Thanks for your sharing.
I have google for a while, but there is seldom document mention about how to implement a device on qemu.You really helped me a great favor!!!

I am going to add a device on qemu which the platform I have to emulate is verstatilepb.
After reading README.md, I have two questions that I still can't figure them out by myself...

1. after adding driver_pic.c to qemu/hw/char, what content should I add to Makefile?

2. if I must use verstatilepb platform, how to add device to verstatilepb?
   (i don't understand how to use tic3.dts and versatilepb.c file)

I am wondering maybe can discuss these issue with you.
Thank you anyway~~

**Comment by grandemk** [comment]
Hi, sorry, it's been a long time since I've done these. I don't think they compile anymore against the master of qemu.

2. In versatilepb,  adding the device was done in the code  vith sysbus_create_simple("test_tic", 0x101f5000, pic[15]);

the device tree is not used by qemu but given to the kernel as a description of the hw below. It describes the versatilepb platform. As we changed the versatilepb platform by adding our own custom device, the device tree must reflect the new state of the hardware.

We compile the device tree in a binary blob:
dtc -O dtb -I dts -o tic.dtb tic2.dts
And then qemu place it somewhere in memory and tell uboot / the kernel where to find it.
/path_to_your_qemu/arm-softmmu/qemu-system-arm -M versatilepb -kernel output/images/zImage -append "root=/dev/ram console=ttyAMA0,115200 earlyprintk" -nographic -dtb tic.dtb
